services:
    app:
        build:
            context: .
            args:
                - USERNAME=${USER}
        command: sleep infinity
        volumes:
            - vscode-extension-volume:/root/.vscode-server/extensions
            - ../..:/workspaces:cached

volumes:
    vscode-extension-volume: {}
